# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backupfile', models.CharField(max_length=256, verbose_name='\u5907\u4efd\u6587\u4ef6\u540d')),
                ('backstatus', models.IntegerField(choices=[(0, '\u6210\u529f'), (1, '\u5931\u8d25'), (2, '\u672a\u6267\u884c'), (3, '\u5df2\u56de\u6eda')], default=2)),
                ('backuppath', models.CharField(max_length=256, verbose_name='\u5907\u4efd\u8def\u5f84')),
                ('backuptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5907\u4efd\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadpath', models.CharField(max_length=256, verbose_name='\u4e0b\u8f7d\u6587\u4ef6\u8def\u5f84')),
                ('checkouttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkoutstatus', models.IntegerField(choices=[(0, '\u6210\u529f'), (1, '\u5931\u8d25'), (2, '\u672a\u6267\u884c'), (3, '\u5df2\u56de\u6eda')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='CoreApply',
            fields=[
                ('name', models.CharField(max_length=128, verbose_name='\u6295\u4ea7\u540d\u79f0')),
                ('inputurl', models.CharField(max_length=256, verbose_name='\u7528\u6237\u8f93\u5165svn\u5730\u5740')),
                ('choicetype', models.IntegerField(choices=[(0, '\u65b0\u4efb\u52a1'), (1, 'BUG\u4fee\u590d'), (2, '\u672a\u6267\u884c')], default=2, verbose_name='\u6295\u4ea7\u7c7b\u578b')),
                ('applytime', models.DateTimeField(default=django.utils.timezone.now)),
                ('applystatus', models.IntegerField(choices=[(0, '\u6210\u529f'), (1, '\u5931\u8d25'), (2, '\u672a\u6267\u884c'), (3, '\u5df2\u56de\u6eda')], default=2)),
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=256, verbose_name='\u66f4\u65b0\u6587\u4ef6')),
                ('serverpath', models.CharField(max_length=256, verbose_name='\u670d\u52a1\u5668\u8def\u5f84')),
                ('execument', models.IntegerField(choices=[(0, '\u6dfb\u52a0'), (1, '\u66ff\u6362'), (2, '\u5f02\u5e38')])),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoreApply')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runip', models.CharField(max_length=256, verbose_name='ip\u5730\u5740')),
                ('linenum', models.IntegerField(default=0)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoreApply')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedProecss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(default=0)),
                ('conment', models.CharField(max_length=256, verbose_name='\u6267\u884c\u5185\u5bb9')),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoreApply')),
            ],
        ),
        migrations.CreateModel(
            name='SvnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256, verbose_name='\u4e0a\u4f20\u6587\u4ef6\u540d')),
                ('svnfilepath', models.CharField(max_length=256, verbose_name='SVN\u4e0a\u4f20\u6587\u4ef6\u8def\u5f84')),
                ('upload_user', models.CharField(max_length=32, verbose_name='\u4e0a\u4f20\u4eba')),
                ('file_upload_at', models.DateTimeField(verbose_name='\u4e0a\u4f20\u65e5\u671f')),
                ('commit_revision', models.IntegerField(verbose_name='\u63d0\u4ea4\u7248\u672c\u53f7')),
                ('commit_size', models.IntegerField(verbose_name='\u63d0\u4ea4\u5927\u5c0f')),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoreApply')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(max_length=64, verbose_name='\u6a21\u677f\u540d\u79f0')),
                ('applyipaddr', models.CharField(max_length=256, verbose_name='\u5e94\u7528\u670d\u52a1\u5668\u5730\u5740')),
                ('applypath', models.CharField(max_length=256, verbose_name='\u7a0b\u5e8f\u90e8\u7f72\u8def\u5f84')),
                ('logpath', models.CharField(max_length=256, verbose_name='\u542f\u52a8\u65e5\u5fd7\u8def\u5f84')),
                ('runcommand', models.CharField(max_length=256, verbose_name='\u6267\u884c\u547d\u4ee4')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=32, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=32, verbose_name='\u5ea7\u673a')),
                ('mobile', models.CharField(max_length=32, verbose_name='\u624b\u673a')),
                ('memo', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='coreapply',
            name='applyuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='coreapply',
            name='userproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='coreapply',
            name='usertemp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TemplateMsg'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoreApply'),
        ),
        migrations.AddField(
            model_name='backup',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoreApply'),
        ),
    ]
