#!/usr/bin/env python

import commands
import random
from string import digits
from string import ascii_letters as letters

def mkpasswd():
    return ''.join([random.choice(letters + digits) for i in range(12)])

def create_dict():
    d = dict()
    old_passwd_file = open('./keepass.txt','r')
    for i in old_passwd_file.readlines():
        ip = i.split()[0]
        beizhu = i.split()[3]
        d[ip] = beizhu
    old_passwd_file.close()
    return d

def minion_list():
    return commands.getoutput('salt-key -L').split('\n')

if __name__ == "__main__":
    new_passwd_file = open('./keepass_new.txt','w+')
    for k,v in create_dict().items():
        if k in minion_list():
            p = mkpasswd()
            shadow_p = commands.getoutput('openssl passwd -1 ' + p)
            commands.getoutput("salt "+k+" shadow.set_password root '"+shadow_p+"'")
            new_passwd_file.write(k + ',' + p + ',' + v + '\n')
        else:
            new_passwd_file.write(k + ',' + 'no change\n')
    new_passwd_file.close()
